.left-category-area .category-header h4,
.section-title h2::before,
.product-card .countdown span,
.flash-deal-slider.owl-carousel .owl-nav div:hover,
.features-slider.owl-carousel .owl-nav div:hover,
.newproduct-slider.owl-carousel .owl-nav div:hover,
.bestseller-slider.owl-carousel .owl-nav div:hover,
.toprated-slider.owl-carousel .owl-nav div:hover,
.pagination li a:hover, .pagination li span:hover,
.pagination li.active span, .pagination li.active a,
.nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active,
.u-d-d i,
.details-page-top-right-content .countdown span,
.mm-heading-area,
.section-title .links a::before,
.flash-sell-area.theme2 .product-card .countdown,
.menu-top-area,
.product-card .product-button-group .product-button,
.deal-of-day-section .countdown,
.bestseller-slider.owl-carousel .owl-nav div:hover, 
.brand-slider.owl-carousel .owl-nav div:hover, 
.features-slider.owl-carousel .owl-nav div:hover, 
.flash-deal-slider.owl-carousel .owl-nav div:hover, 
.home-blog-slider.owl-carousel .owl-nav div:hover, 
.newproduct-slider.owl-carousel .owl-nav div:hover, 
.popular-category-slider.owl-carousel .owl-nav div:hover, 
.toprated-slider.owl-carousel .owl-nav div:hover,
.btn,
.footer-social-links a,
.a2a_kit a
{
    background : {{ $color }} !important;
}

.site-header .toolbar .toolbar-item > a > div > .compare-icon > .count-label, .site-header .toolbar .toolbar-item > a > div > .cart-icon > .count-label,
.btn-primary,
.hero-slider > .owl-carousel.dots-inside .owl-dots .owl-dot,
.widget-title::after,
.scroll-to-top-btn:hover,
.review-item .review-start span,
.badge-success,
.badge-danger,
.quantity-selector .qty-decrease:hover, .quantity-selector .qty-increase:hover,
.price-slider .noUi-connect,
.loading-icon i,
.star-rating i,
.sidebar-widget.categories-list .cat-item a:hover,
.sidebar-widget.filter-price .price-range-content .price-reset,
.sidebar-widget.filter-attributes .cat-item .cat-checkbox:checked ~ .cat-name::before,
.sidebar-widget .filter-title::before,
.deal-badge,
.product-grid .product-card:hover .product-button,
.product-card .product-inner:hover .product-button,
.product-tabs .nav-link.active::after,
.product-description-tab .item:hover .item-icon i,
.review-form .rating-input .rating-icon.active,
.product-gallery .owl-nav div:hover,
.product-video-button,
.slick-slide button:hover,
.header-search-box .btn,
.select2-container--classic.select2-container--open .select2-selection--single,
.select2-container--classic .select2-selection--single .select2-selection__clear::before,
.select2-container--default .select2-results__option--highlighted[aria-selected],
.daterangepicker .applyBtn,
.daterangepicker .applyBtn:hover,
.checkout-step-heading .step-icon,
.breadcrumb li.active a,
.checkout-form .form-group label,
.checkout-item-header .checkout-method-item label:hover .method-item-name,
.checkout-payment-method .payment-btn:hover .payment-method-icon,
.checkout-payment-method .payment-btn.active .payment-method-icon,
.payment-info .info-icon,
.order-success-wrap .success-badge,
.order-track-wrap .step-icon.completed,
.faq-item:hover .faq-item-question,
.faq-item.active .faq-item-question,
.page-control a:hover,
.page-control a.active,
.breadcrumb a:hover,
.breadcrumb li.active a,
.contact-info-card .contact-icon,
.featured-category-slider .featured-category-card:hover .featured-category-name,
.featured-category-item:hover .featured-category-name,
.blog-card:hover .blog-card-date,
.list-group-item:hover a,
.blog-sidebar .blog-categories .cat-item a:hover,
.blog-sidebar .blog-categories .cat-item.active a,
.blog-sidebar .recent-blog-item:hover .recent-blog-date,
.blog-single-page.right-sidebar .blog-categories .cat-item a:hover,
.blog-single-page.right-sidebar .blog-categories .cat-item.active a,
.blog-comment-reply:hover,
.blog-comment-form .rating-input .rating-icon.active,
.vendor-list-card:hover .vendor-list-name,
.vendor-list-card:hover .vendor-link,
.vendor-single-header .vendor-header-bottom .vendor-item:hover,
.vendor-detail-tab .nav-link.active,
.vendor-detail-tab .nav-link.active::after,
.vendor-list-page .nav-link.active,
.vendor-product-item:hover .product-button
{
    color: {{ $color }} !important;
}

.breadcrumb a:hover,
.widget-title::after,
.sidebar-list-item a:hover,
.mega-menu .menu-item.active,
.navbar .navbar-collapse .navbar-menu a.active,
.navbar .navbar-collapse .navbar-menu a:hover,
.wishlist-card:hover .wishlist-card-share,
.product-tabs .nav-link:hover::after,
.product-tabs .nav-link.active::after,
.navbar-collapse .navbar-menu a:hover::before,
.navbar-collapse .navbar-menu a.active::before,
.sidebar-list-item a:hover::after,
.product-card .product-inner:hover .product-button,
.breadcrumb li:last-child::before,
.wishlist-card .compare-remove:hover,
.contact-form .btn
{
    border-color: {{ $color }} !important;
}

.breadcrumb li.active a::after,
.product-card:hover .product-button,
.hero-slider > .owl-carousel .owl-nav div:hover,
.blog-card,
.flash-deal-slider.owl-carousel .owl-nav div:hover,
.product-grid .product-card:hover,
.product-card:hover,
.featured-category-slider .featured-category-card:hover,
.featured-category-item:hover,
.vendor-list-card:hover,
.blog-card:hover,
.brand-card:hover,
.service-item:hover,
.testimonial-card.active .card,
.testimonial-card.active
{
    box-shadow: 0 8px 24px {{ $color }}33 !important;
}

.breadcrumb li::after,
.pagination li a:hover, .pagination li span:hover,
.pagination li.active span, .pagination li.active a,
.product-grid .product-card .product-inner:hover::before,
.header-search-box .btn-search,
.select-group .nice-select::after,
.select2-container--default .select2-selection--single .select2-selection__arrow b,
.input-group-file input[type=file]::-webkit-file-upload-button,
.hero-slider .item-inner::before,
.hero-slider .item-inner::after,
.hero-slider > .owl-carousel .owl-nav div,
.hero-slider > .owl-carousel .owl-nav div:hover,
.best-sellng-inner .owl-nav .owl-prev:hover,
.best-sellng-inner .owl-nav .owl-next:hover,
.features-slider.owl-carousel .owl-nav div,
.features-slider.owl-carousel .owl-nav div:hover,
.flash-deal-slider.owl-carousel .owl-nav div,
.flash-deal-slider.owl-carousel .owl-nav div:hover,
.newproduct-slider.owl-carousel .owl-nav div,
.newproduct-slider.owl-carousel .owl-nav div:hover,
.bestseller-slider.owl-carousel .owl-nav div,
.bestseller-slider.owl-carousel .owl-nav div:hover,
.toprated-slider.owl-carousel .owl-nav div,
.toprated-slider.owl-carousel .owl-nav div:hover,
.brand-slider.owl-carousel .owl-nav div,
.brand-slider.owl-carousel .owl-nav div:hover,
.home-blog-slider.owl-carousel .owl-nav div,
.home-blog-slider.owl-carousel .owl-nav div:hover,
.popular-category-slider.owl-carousel .owl-nav div,
.popular-category-slider.owl-carousel .owl-nav div:hover,
.product-gallery .owl-nav div,
.product-gallery .owl-nav div:hover,
.scroll-to-top-btn,
.pagination li.active span, .pagination li.active a,
.sidebar-widget .filter-title::before,
.checkout-step-heading .step-icon,
.vendor-list-card:hover .vendor-link,
.blog-card:hover .blog-card-date
{
    background-color: {{ $color }} !important;
}

.product-badge.badge-sale,
.product-badge.badge-new,
.deal-badge,
.hero-slider .item-inner .offer-badge,
.countdown-badge,
.stock-out-badge,
.breadcrumb li.active a::before,
.pagination li a:hover, .pagination li span:hover,
.pagination li.active span, .pagination li.active a,
.blog-sidebar .blog-categories .cat-item a:hover,
.blog-sidebar .blog-categories .cat-item.active a,
.blog-single-page.right-sidebar .blog-categories .cat-item a:hover,
.blog-single-page.right-sidebar .blog-categories .cat-item.active a
{
    background-color: {{ $color }} !important;
}
